apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: m-yd-7cqe-nodejs 
  janus-idp.io/tekton: m-yd-7cqe-nodejs
  backstage.io/kubernetes-id: m-yd-7cqe-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: m-yd-7cqe-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  